name: Send Email

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # nodemailer 설치
      - name: Install dependencies
        run: npm install nodemailer

      # sendEmail.js 실행
      - name: Send email
        run: |
          node ./post_office/send_email.js
          
      # Secret에 설정한 변수를 환경 변수로 설정
        env:
          EMAIL_ID: ${{ secrets.EMAIL_ID }}
          PASSWORD: ${{ secrets.PASSWORD }}
